#!/bin/bash

# By: Daniele Bertagnoli

#  ____           _____ _    _ 
# |  _ \   /\    / ____| |  | |
# | |_) | /  \  | (___ | |__| |
# |  _ < / /\ \  \___ \|  __  |
# | |_) / ____ \ ____) | |  | |
# |____/_/    \_\_____/|_|  |_|
#

# IMPORTANT NOTE: Do not edit this file, you adjust the configuration by editing or adding files in ~/.config/bashrc

for f in ~/.config/bashrc/*; do
	if [ ! -d $f ]; then
		source $f
	fi
done
