windowrule = float on on, match:title ^(pavucontrol)$
windowrule = float on, match:title ^(blueman-manager)$
windowrule = float on, match:title ^(nm-connection-editor)$
windowrule = tile on, match:title ^(qiv)$

# Browser Picture in Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 69.5% 4%, match:title ^(Picture-in-Picture)$

# Pavucontrol float oning
windowrule = float on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = size 700 600,match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = center on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = pin on, match:class (.*org.pulseaudio.pavucontrol.*)

# System Mission Center
windowrule = float on, match:class (io.missioncenter.MissionCenter)
windowrule = pin on, match:class (io.missioncenter.MissionCenter)
windowrule = center on, match:class (io.missioncenter.MissionCenter)
windowrule = size 900 600, match:class (io.missioncenter.MissionCenter)

# System Mission Center Preference Window
windowrule = float on, match:class (missioncenter), match:title ^(Preferences)$
windowrule = pin on, match:class (missioncenter), match:title ^(Preferences)$
windowrule = center on, match:class (missioncenter), match:title ^(Preferences)$

# Gnome Calculator
windowrule = float on,match:class (org.gnome.Calculator)
windowrule = size 700 600,match:class (org.gnome.Calculator)
windowrule = center on,match:class (org.gnome.Calculator)

# Hyprland Share Picker
windowrule = float on, match:class (hyprland-share-picker)
windowrule = pin on, match:class (hyprland-share-picker)
windowrule = center on, match:title match:class (hyprland-share-picker)
windowrule = size 600 400,match:class (hyprland-share-picker)

# General float oning
windowrule = float on,match:class (dotfiles-float oning)
windowrule = size 1000 700,match:class (dotfiles-float oning)
windowrule = center on,match:class (dotfiles-float oning)
windowrule = pin on, match:class (dotfiles-float oning)

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GDK
env = GDK_SCALE,1

# Toolkit Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24

# Disable appimage launcher by default
env = APPIMAGELAUNCHER_DISABLE,1

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
